// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use crate::{ db::Connection, schema::* };
use bigdecimal::BigDecimal;
use chrono::NaiveDateTime;
use diesel::{ PgConnection, Queryable };

#[derive(Queryable, Debug)]
pub struct Order {
    pub id: i32,
    pub status: i16,
    pub created_at: NaiveDateTime,
    pub customer_id: i32,
    pub payment_method_id: i32,
    pub shipping_information_id: i32,
    pub store_id: i32,
    pub total_discount: Option<BigDecimal>,
    pub total_price: BigDecimal,
}

#[derive(Queryable, Debug)]
pub struct OrderItem {
    pub id: i32,
    pub quantity: i32,
    pub order_id: Option<i32>,
    pub product_item_id: i32,
    pub shopping_cart_id: Option<i32>,
    pub unit_price: BigDecimal,
}

#[derive(Queryable, Debug)]
pub struct Product {
    pub id: i32,
    pub name: String,
    pub deleted: bool,
    pub category_id: i32,
    pub store_id: i32,
}

#[derive(Queryable, Debug)]
pub struct ProductCategory {
    pub id: i32,
    pub name: String,
    pub store_id: i32,
}

#[derive(Queryable, Debug)]
pub struct ProductDiscount {
    pub id: i32,
    pub percentual: BigDecimal,
    pub created_at: NaiveDateTime,
    pub expires_at: NaiveDateTime,
    pub store_id: i32,
}

#[derive(Queryable, Debug)]
pub struct ProductItem {
    pub id: i32,
    pub sku: Option<String>,
    pub description: Option<String>,
    pub price: BigDecimal,
    pub stock: i32,
    pub deleted: bool,
    pub created_at: NaiveDateTime,
    pub discount_id: Option<i32>,
    pub image_url: Option<String>,
    pub product_id: i32,
    pub store_id: i32,
    pub updated_at: NaiveDateTime,
    pub variant_id: Option<i32>,
}

#[derive(Queryable, Debug)]
pub struct ProductVariant {
    pub id: i32,
    pub name: String,
    pub value: String,
    pub store_id: i32,
}

#[derive(Queryable, Debug)]
pub struct ShippingInformation {
    pub id: i32,
    pub status: i32,
    pub address_id: i32,
    pub created_at: NaiveDateTime,
    pub shipping_method_id: i32,
    pub shipping_price: BigDecimal,
    pub tracking_number: Option<String>,
    pub updated_at: NaiveDateTime,
}

#[derive(Queryable, Debug)]
pub struct ShoppingCart {
    pub id: i32,
    pub created_at: NaiveDateTime,
    pub customer_id: i32,
    pub store_id: i32,
}
