// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use bigdecimal::BigDecimal;
use chrono::NaiveDateTime;
use diesel::Queryable;

#[derive(Queryable, Debug)]
pub struct Order {
    pub id: i32,
    pub status: i16,
    pub created_at: NaiveDateTime,
    pub customer_id: i32,
    pub payment_method_id: i32,
    pub shipping_information_id: i32,
    pub store_id: i32,
    pub total_discount: Option<BigDecimal>,
    pub total_price: BigDecimal,
}

#[derive(Queryable, Debug)]
pub struct OrderItem {
    pub id: i32,
    pub quantity: i32,
    pub order_id: Option<i32>,
    pub product_item_id: i32,
    pub shopping_cart_id: Option<i32>,
    pub unit_price: BigDecimal,
}

#[derive(Queryable, Debug)]
pub struct PaymentMethod {
    pub id: i32,
    pub name: String,
    pub inactive: bool,
    pub deleted: bool,
    pub created_at: NaiveDateTime,
    pub store_id: i32,
    pub updated_at: NaiveDateTime,
}

#[derive(Queryable, Debug)]
pub struct Product {
    pub id: i32,
    pub name: String,
    pub deleted: bool,
    pub category_id: i32,
    pub store_id: i32,
}

#[derive(Queryable, Debug)]
pub struct ProductCategory {
    pub id: i32,
    pub name: String,
    pub store_id: i32,
}

#[derive(Queryable, Debug)]
pub struct ProductDiscount {
    pub id: i32,
    pub percentual: BigDecimal,
    pub created_at: NaiveDateTime,
    pub expires_at: NaiveDateTime,
    pub store_id: i32,
}

#[derive(Queryable, Debug)]
pub struct ProductItem {
    pub id: i32,
    pub sku: Option<String>,
    pub description: Option<String>,
    pub price: BigDecimal,
    pub stock: i32,
    pub deleted: bool,
    pub created_at: NaiveDateTime,
    pub discount_id: Option<i32>,
    pub image_url: Option<String>,
    pub product_id: i32,
    pub store_id: i32,
    pub updated_at: NaiveDateTime,
    pub variant_id: Option<i32>,
}

#[derive(Queryable, Debug)]
pub struct ProductVariant {
    pub id: i32,
    pub name: String,
    pub value: String,
    pub store_id: i32,
}

#[derive(Queryable, Debug)]
pub struct ShippingInformation {
    pub id: i32,
    pub status: i32,
    pub address_id: i32,
    pub created_at: NaiveDateTime,
    pub shipping_method_id: i32,
    pub shipping_price: BigDecimal,
    pub tracking_number: Option<String>,
    pub updated_at: NaiveDateTime,
}

#[derive(Queryable, Debug)]
pub struct ShippingMethod {
    pub id: i32,
    pub name: String,
    pub inactive: bool,
    pub deleted: bool,
    pub created_at: NaiveDateTime,
    pub store_id: i32,
    pub updated_at: NaiveDateTime,
}

#[derive(Queryable, Debug)]
pub struct ShoppingCart {
    pub id: i32,
    pub created_at: NaiveDateTime,
    pub customer_id: i32,
    pub store_id: i32,
}

#[derive(Queryable, Debug)]
pub struct Store {
    pub id: i32,
    pub name: String,
    pub created_at: NaiveDateTime,
    pub logo_url: Option<String>,
    pub updated_at: NaiveDateTime,
}

#[derive(Queryable, Debug)]
pub struct StoreInvite {
    pub id: String,
    pub valid: bool,
    pub created_at: NaiveDateTime,
    pub store_id: i32,
}

#[derive(Queryable, Debug)]
pub struct User {
    pub id: i32,
    pub email: String,
    pub password: String,
    pub type_: i32,
    pub created_at: NaiveDateTime,
    pub first_name: String,
    pub last_login: NaiveDateTime,
    pub last_name: String,
    pub managed_store_id: Option<i32>,
    pub updated_at: NaiveDateTime,
    pub salt: String,
}

#[derive(Queryable, Debug)]
pub struct UserAddres {
    pub id: i32,
    pub number: String,
    pub city: String,
    pub country: String,
    pub deleted: bool,
    pub address_line1: String,
    pub address_line2: Option<String>,
    pub created_at: NaiveDateTime,
    pub phone_country_code: Option<String>,
    pub phone_number: Option<String>,
    pub postal_code: String,
    pub updated_at: NaiveDateTime,
    pub user_id: i32,
}
